DECLARE
    PROCEDURE exec_ddl(p_sql IN CLOB) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -955 THEN
                NULL;
            ELSE
                RAISE;
            END IF;
    END;
BEGIN
    exec_ddl('CREATE TABLE CMH.DEPARTMENTS (
        ID NUMBER NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        DESCRIPTION VARCHAR2(255),
        LOCATION VARCHAR2(100),
        HEAD_STAFF_ID NUMBER,
        DEPT_CODE VARCHAR2(30),
        IS_ACTIVE CHAR(1) NOT NULL,
        SORT_ORDER NUMBER NOT NULL,
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE,
        BUILDING_NO VARCHAR2(50),
        FLOOR_NO VARCHAR2(10),
        ROOM_NO VARCHAR2(20),
        EXTENSION VARCHAR2(20)
    )');

    exec_ddl('CREATE TABLE CMH.POSITIONS (
        ID NUMBER NOT NULL,
        DOMAIN VARCHAR2(50),
        TITLE VARCHAR2(100),
        DESCRIPTION VARCHAR2(255),
        POSITION_CODE VARCHAR2(30),
        IS_ACTIVE CHAR(1) NOT NULL,
        SORT_ORDER NUMBER NOT NULL,
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.STAFF_STATUS_CODES (
        CODE VARCHAR2(20) NOT NULL,
        LABEL VARCHAR2(50) NOT NULL,
        SORT_ORDER NUMBER NOT NULL,
        IS_ACTIVE CHAR(1) NOT NULL,
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.STAFF (
        ID NUMBER NOT NULL,
        USERNAME VARCHAR2(50) NOT NULL,
        PASSWORD_HASH VARCHAR2(64),
        STATUS VARCHAR2(20),
        DOMAIN_ROLE VARCHAR2(50),
        FULL_NAME VARCHAR2(100),
        OFFICE_LOCATION VARCHAR2(255),
        PHOTO_KEY VARCHAR2(255),
        BIO CLOB,
        PHONE VARCHAR2(20),
        DEPT_ID NUMBER,
        POSITION_ID NUMBER,
        STATUS_CODE VARCHAR2(20),
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.STAFF_CREDENTIAL (
        ID NUMBER(10) NOT NULL,
        STAFF_ID NUMBER(10) NOT NULL,
        CRED_TYPE VARCHAR2(10) NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        CRED_NUMBER VARCHAR2(50),
        ISSUER VARCHAR2(100),
        ISSUED_AT DATE,
        EXPIRES_AT DATE,
        STATUS VARCHAR2(20) NOT NULL,
        EVIDENCE_KEY VARCHAR2(255),
        CREATED_AT DATE,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.VISIT_REG (
        ID NUMBER NOT NULL,
        VISIT_NO VARCHAR2(30),
        PATIENT_ID NUMBER NOT NULL,
        PATIENT_NO VARCHAR2(30),
        PATIENT_NAME VARCHAR2(100),
        PATIENT_PHONE VARCHAR2(20),
        VISIT_TYPE VARCHAR2(30) NOT NULL,
        STATUS VARCHAR2(30) NOT NULL,
        DEPT_CODE VARCHAR2(50) NOT NULL,
        DOCTOR_ID VARCHAR2(50),
        PRIORITY_YN NUMBER(1),
        QUEUE_NO NUMBER,
        CALLED_AT DATE,
        STARTED_AT DATE,
        FINISHED_AT DATE,
        MEMO VARCHAR2(1000),
        CANCELLED_AT DATE,
        CANCEL_REASON_CODE VARCHAR2(50),
        CANCEL_MEMO VARCHAR2(1000),
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.VISIT_HISTORY (
        ID NUMBER NOT NULL,
        VISIT_ID NUMBER NOT NULL,
        EVENT_TYPE VARCHAR2(30),
        FIELD_NAME VARCHAR2(50),
        OLD_VALUE VARCHAR2(1000),
        NEW_VALUE VARCHAR2(1000),
        REASON VARCHAR2(500),
        CHANGED_BY VARCHAR2(50),
        CHANGED_AT DATE NOT NULL
    )');

    exec_ddl('CREATE TABLE CMH.VISIT_RESERVATION (
        VISIT_ID NUMBER NOT NULL,
        RESERVATION_ID VARCHAR2(50),
        SCHEDULED_AT DATE,
        ARRIVAL_AT DATE,
        NOTE VARCHAR2(1000),
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.VISIT_EMERGENCY (
        VISIT_ID NUMBER NOT NULL,
        TRIAGE_LEVEL VARCHAR2(20),
        AMBULANCE_YN NUMBER(1),
        TRAUMA_YN NUMBER(1),
        NOTE VARCHAR2(1000),
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.VISIT_INPATIENT (
        VISIT_ID NUMBER NOT NULL,
        WARD_CODE VARCHAR2(30),
        ROOM_NO VARCHAR2(30),
        BED_NO VARCHAR2(30),
        ADMISSION_AT DATE,
        NOTE VARCHAR2(1000),
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.MEDICAL_ENCOUNTER (
        ID NUMBER NOT NULL,
        VISIT_ID NUMBER NOT NULL,
        PATIENT_ID NUMBER NOT NULL,
        PATIENT_NO VARCHAR2(30),
        PATIENT_NAME VARCHAR2(100),
        DOCTOR_ID VARCHAR2(50),
        DEPT_CODE VARCHAR2(50),
        STATUS VARCHAR2(30) NOT NULL,
        CHIEF_COMPLAINT VARCHAR2(2000),
        ASSESSMENT VARCHAR2(2000),
        PLAN_NOTE VARCHAR2(2000),
        DIAGNOSIS_CODE VARCHAR2(100),
        MEMO VARCHAR2(2000),
        IS_ACTIVE CHAR(1) NOT NULL,
        INACTIVE_REASON_CODE VARCHAR2(50),
        INACTIVE_REASON_MEMO VARCHAR2(1000),
        INACTIVATED_AT DATE,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT DATE NOT NULL,
        UPDATED_AT DATE
    )');

    exec_ddl('CREATE TABLE CMH.MEDICAL_ENCOUNTER_HISTORY (
        ID NUMBER NOT NULL,
        ENCOUNTER_ID NUMBER NOT NULL,
        EVENT_TYPE VARCHAR2(30),
        FIELD_NAME VARCHAR2(50),
        OLD_VALUE VARCHAR2(2000),
        NEW_VALUE VARCHAR2(2000),
        REASON VARCHAR2(500),
        CHANGED_BY VARCHAR2(50),
        CHANGED_AT DATE NOT NULL
    )');

    exec_ddl('CREATE TABLE LHS.MENU (
        ID NUMBER NOT NULL,
        PARENT_ID NUMBER,
        CODE VARCHAR2(50) NOT NULL,
        NAME VARCHAR2(100) NOT NULL,
        PATH VARCHAR2(200),
        ICON VARCHAR2(50),
        SORT_ORDER NUMBER NOT NULL,
        IS_ACTIVE NUMBER(1) NOT NULL,
        CREATED_AT TIMESTAMP(6) NOT NULL,
        UPDATED_AT TIMESTAMP(6) NOT NULL
    )');
END;
/

DECLARE
    PROCEDURE add_constraint_if_missing(p_owner IN VARCHAR2, p_table IN VARCHAR2, p_name IN VARCHAR2, p_ddl IN CLOB) IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_cnt
          FROM ALL_CONSTRAINTS
         WHERE OWNER = UPPER(p_owner)
           AND TABLE_NAME = UPPER(p_table)
           AND CONSTRAINT_NAME = UPPER(p_name);

        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_constraint_if_missing('CMH', 'DEPARTMENTS', 'PK_DEPARTMENTS',
        'ALTER TABLE CMH.DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'POSITIONS', 'PK_POSITIONS',
        'ALTER TABLE CMH.POSITIONS ADD CONSTRAINT PK_POSITIONS PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'STAFF_STATUS_CODES', 'PK_STAFF_STAT_CD',
        'ALTER TABLE CMH.STAFF_STATUS_CODES ADD CONSTRAINT PK_STAFF_STAT_CD PRIMARY KEY (CODE)');
    add_constraint_if_missing('CMH', 'STAFF', 'PK_STAFF',
        'ALTER TABLE CMH.STAFF ADD CONSTRAINT PK_STAFF PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'STAFF_CREDENTIAL', 'PK_STAFF_CRED',
        'ALTER TABLE CMH.STAFF_CREDENTIAL ADD CONSTRAINT PK_STAFF_CRED PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'VISIT_REG', 'PK_VISIT_REG',
        'ALTER TABLE CMH.VISIT_REG ADD CONSTRAINT PK_VISIT_REG PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'VISIT_HISTORY', 'PK_VISIT_HISTORY',
        'ALTER TABLE CMH.VISIT_HISTORY ADD CONSTRAINT PK_VISIT_HISTORY PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'VISIT_RESERVATION', 'PK_VISIT_RESERVATION',
        'ALTER TABLE CMH.VISIT_RESERVATION ADD CONSTRAINT PK_VISIT_RESERVATION PRIMARY KEY (VISIT_ID)');
    add_constraint_if_missing('CMH', 'VISIT_EMERGENCY', 'PK_VISIT_EMERGENCY',
        'ALTER TABLE CMH.VISIT_EMERGENCY ADD CONSTRAINT PK_VISIT_EMERGENCY PRIMARY KEY (VISIT_ID)');
    add_constraint_if_missing('CMH', 'VISIT_INPATIENT', 'PK_VISIT_INPATIENT',
        'ALTER TABLE CMH.VISIT_INPATIENT ADD CONSTRAINT PK_VISIT_INPATIENT PRIMARY KEY (VISIT_ID)');
    add_constraint_if_missing('CMH', 'MEDICAL_ENCOUNTER', 'PK_MEDICAL_ENCOUNTER',
        'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT PK_MEDICAL_ENCOUNTER PRIMARY KEY (ID)');
    add_constraint_if_missing('CMH', 'MEDICAL_ENCOUNTER_HISTORY', 'PK_MED_ENC_HIS',
        'ALTER TABLE CMH.MEDICAL_ENCOUNTER_HISTORY ADD CONSTRAINT PK_MED_ENC_HIS PRIMARY KEY (ID)');
    add_constraint_if_missing('LHS', 'MENU', 'PK_MENU',
        'ALTER TABLE LHS.MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (ID)');

    add_constraint_if_missing('CMH', 'STAFF', 'FK_STAFF_DEPT',
        'ALTER TABLE CMH.STAFF ADD CONSTRAINT FK_STAFF_DEPT FOREIGN KEY (DEPT_ID) REFERENCES CMH.DEPARTMENTS(ID)');
    add_constraint_if_missing('CMH', 'STAFF', 'FK_STAFF_POS',
        'ALTER TABLE CMH.STAFF ADD CONSTRAINT FK_STAFF_POS FOREIGN KEY (POSITION_ID) REFERENCES CMH.POSITIONS(ID)');
    add_constraint_if_missing('CMH', 'STAFF', 'FK_STAFF_STAT_CD',
        'ALTER TABLE CMH.STAFF ADD CONSTRAINT FK_STAFF_STAT_CD FOREIGN KEY (STATUS_CODE) REFERENCES CMH.STAFF_STATUS_CODES(CODE)');
    add_constraint_if_missing('CMH', 'STAFF_CREDENTIAL', 'FK_STFCRD_STAFF',
        'ALTER TABLE CMH.STAFF_CREDENTIAL ADD CONSTRAINT FK_STFCRD_STAFF FOREIGN KEY (STAFF_ID) REFERENCES CMH.STAFF(ID)');
    add_constraint_if_missing('CMH', 'VISIT_HISTORY', 'FK_VISIT_HIS_VISIT',
        'ALTER TABLE CMH.VISIT_HISTORY ADD CONSTRAINT FK_VISIT_HIS_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)');
    add_constraint_if_missing('CMH', 'VISIT_RESERVATION', 'FK_VISIT_RES_VISIT',
        'ALTER TABLE CMH.VISIT_RESERVATION ADD CONSTRAINT FK_VISIT_RES_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)');
    add_constraint_if_missing('CMH', 'VISIT_EMERGENCY', 'FK_VISIT_EMG_VISIT',
        'ALTER TABLE CMH.VISIT_EMERGENCY ADD CONSTRAINT FK_VISIT_EMG_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)');
    add_constraint_if_missing('CMH', 'VISIT_INPATIENT', 'FK_VISIT_INP_VISIT',
        'ALTER TABLE CMH.VISIT_INPATIENT ADD CONSTRAINT FK_VISIT_INP_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)');
    add_constraint_if_missing('CMH', 'MEDICAL_ENCOUNTER', 'FK_MED_ENC_VISIT',
        'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT FK_MED_ENC_VISIT FOREIGN KEY (VISIT_ID) REFERENCES CMH.VISIT_REG(ID)');
    add_constraint_if_missing('CMH', 'MEDICAL_ENCOUNTER_HISTORY', 'FK_MED_ENC_HIS_ENC',
        'ALTER TABLE CMH.MEDICAL_ENCOUNTER_HISTORY ADD CONSTRAINT FK_MED_ENC_HIS_ENC FOREIGN KEY (ENCOUNTER_ID) REFERENCES CMH.MEDICAL_ENCOUNTER(ID)');

    add_constraint_if_missing('CMH', 'DEPARTMENTS', 'CK_DEPT_ACT_YN',
        'ALTER TABLE CMH.DEPARTMENTS ADD CONSTRAINT CK_DEPT_ACT_YN CHECK (IS_ACTIVE IN (''Y'',''N''))');
    add_constraint_if_missing('CMH', 'POSITIONS', 'CK_POS_ACT_YN',
        'ALTER TABLE CMH.POSITIONS ADD CONSTRAINT CK_POS_ACT_YN CHECK (IS_ACTIVE IN (''Y'',''N''))');
    add_constraint_if_missing('CMH', 'STAFF_STATUS_CODES', 'CK_STFSTAT_ACT_YN',
        'ALTER TABLE CMH.STAFF_STATUS_CODES ADD CONSTRAINT CK_STFSTAT_ACT_YN CHECK (IS_ACTIVE IN (''Y'',''N''))');
    add_constraint_if_missing('CMH', 'STAFF_CREDENTIAL', 'CK_STFCRED_TYPE',
        'ALTER TABLE CMH.STAFF_CREDENTIAL ADD CONSTRAINT CK_STFCRED_TYPE CHECK (CRED_TYPE IN (''LICENSE'',''CERT''))');
    add_constraint_if_missing('CMH', 'STAFF_CREDENTIAL', 'CK_STFCRED_STATUS',
        'ALTER TABLE CMH.STAFF_CREDENTIAL ADD CONSTRAINT CK_STFCRED_STATUS CHECK (STATUS IN (''ACTIVE'',''EXPIRED'',''REVOKED''))');
    add_constraint_if_missing('CMH', 'MEDICAL_ENCOUNTER', 'CK_MED_ENC_ACTIVE',
        'ALTER TABLE CMH.MEDICAL_ENCOUNTER ADD CONSTRAINT CK_MED_ENC_ACTIVE CHECK (IS_ACTIVE IN (''Y'',''N''))');
END;
/

DECLARE
    PROCEDURE create_seq_if_missing(p_owner IN VARCHAR2, p_seq IN VARCHAR2) IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_cnt
          FROM ALL_SEQUENCES
         WHERE SEQUENCE_OWNER = UPPER(p_owner)
           AND SEQUENCE_NAME = UPPER(p_seq);

        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_owner || '.' || p_seq || ' START WITH 1 INCREMENT BY 1 NOCACHE';
        END IF;
    END;

    PROCEDURE create_seq_if_missing_start(p_owner IN VARCHAR2, p_seq IN VARCHAR2, p_start IN NUMBER) IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_cnt
          FROM ALL_SEQUENCES
         WHERE SEQUENCE_OWNER = UPPER(p_owner)
           AND SEQUENCE_NAME = UPPER(p_seq);

        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_owner || '.' || p_seq || ' START WITH ' || p_start || ' INCREMENT BY 1 NOCACHE';
        END IF;
    END;

    PROCEDURE create_trigger_if_missing(p_owner IN VARCHAR2, p_trigger IN VARCHAR2, p_sql IN CLOB) IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_cnt FROM ALL_TRIGGERS WHERE OWNER = UPPER(p_owner) AND TRIGGER_NAME = UPPER(p_trigger);
        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    create_seq_if_missing('CMH', 'DEPT_SEQ');
    create_seq_if_missing('CMH', 'POSITION_SEQ');
    create_seq_if_missing('CMH', 'STAFF_SEQ');
    create_seq_if_missing('CMH', 'STAFF_CREDENTIAL_SEQ');
    create_seq_if_missing_start('CMH', 'VISIT_REG_SEQ', 1000);
    create_seq_if_missing_start('CMH', 'VISIT_HISTORY_SEQ', 1000);
    create_seq_if_missing_start('CMH', 'MEDICAL_ENCOUNTER_SEQ', 2000);
    create_seq_if_missing_start('CMH', 'MEDICAL_ENCOUNTER_HIS_SEQ', 2000);

    create_trigger_if_missing('CMH', 'TRG_DEPARTMENTS_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_DEPARTMENTS_ID
         BEFORE INSERT ON CMH.DEPARTMENTS
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.DEPT_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_POSITIONS_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_POSITIONS_ID
         BEFORE INSERT ON CMH.POSITIONS
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.POSITION_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_STAFF_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_STAFF_ID
         BEFORE INSERT ON CMH.STAFF
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.STAFF_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_STAFF_CREDENTIAL_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_STAFF_CREDENTIAL_ID
         BEFORE INSERT ON CMH.STAFF_CREDENTIAL
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.STAFF_CREDENTIAL_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_VISIT_REG_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_VISIT_REG_ID
         BEFORE INSERT ON CMH.VISIT_REG
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.VISIT_REG_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_VISIT_HISTORY_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_VISIT_HISTORY_ID
         BEFORE INSERT ON CMH.VISIT_HISTORY
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.VISIT_HISTORY_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_MEDICAL_ENCOUNTER_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_MEDICAL_ENCOUNTER_ID
         BEFORE INSERT ON CMH.MEDICAL_ENCOUNTER
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.MEDICAL_ENCOUNTER_SEQ.NEXTVAL;
         END;');

    create_trigger_if_missing('CMH', 'TRG_MED_ENC_HIS_ID',
        'CREATE OR REPLACE TRIGGER CMH.TRG_MED_ENC_HIS_ID
         BEFORE INSERT ON CMH.MEDICAL_ENCOUNTER_HISTORY
         FOR EACH ROW
         WHEN (NEW.ID IS NULL)
         BEGIN
           :NEW.ID := CMH.MEDICAL_ENCOUNTER_HIS_SEQ.NEXTVAL;
         END;');
END;
/
