DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM ALL_TABLES WHERE OWNER = 'CMH' AND TABLE_NAME = 'EDI_DIVISION_DICT';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE CMH.EDI_DIVISION_DICT CASCADE CONSTRAINTS';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = 'CMH' AND SEQUENCE_NAME = 'EDI_DIVISION_DICT_SEQ';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP SEQUENCE CMH.EDI_DIVISION_DICT_SEQ';
    END IF;
END;
/
