DECLARE
  PROCEDURE create_index_if_missing(p_owner VARCHAR2, p_index VARCHAR2, p_ddl VARCHAR2) IS
    v_cnt NUMBER := 0;
  BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM ALL_INDEXES
     WHERE OWNER = UPPER(p_owner)
       AND INDEX_NAME = UPPER(p_index);

    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;
BEGIN
  create_index_if_missing('CMH', 'IDX_STAFF_USERNAME', 'CREATE INDEX CMH.IDX_STAFF_USERNAME ON CMH.STAFF (USERNAME)');
  create_index_if_missing('CMH', 'IDX_STAFF_ROLE_DEPT', 'CREATE INDEX CMH.IDX_STAFF_ROLE_DEPT ON CMH.STAFF (DOMAIN_ROLE, DEPT_ID, POSITION_ID)');

  create_index_if_missing('CMH', 'IDX_BOARD_CAT_DEL_DATE', 'CREATE INDEX CMH.IDX_BOARD_CAT_DEL_DATE ON CMH.STAFF_BOARD_POST (CATEGORY, IS_DELETED, EVENT_DATE)');
  create_index_if_missing('CMH', 'IDX_BOARD_CAT_DEL_UPD', 'CREATE INDEX CMH.IDX_BOARD_CAT_DEL_UPD ON CMH.STAFF_BOARD_POST (CATEGORY, IS_DELETED, UPDATED_AT)');
  create_index_if_missing('CMH', 'IDX_BOARD_CAT_POSTTYPE', 'CREATE INDEX CMH.IDX_BOARD_CAT_POSTTYPE ON CMH.STAFF_BOARD_POST (CATEGORY, POST_TYPE)');
  create_index_if_missing('CMH', 'IDX_BOARD_AUTHOR', 'CREATE INDEX CMH.IDX_BOARD_AUTHOR ON CMH.STAFF_BOARD_POST (AUTHOR_ID, CREATED_AT)');

  COMMIT;
END;
/
