BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CMH.LEAVE_REQUEST (
    ID NUMBER(19) PRIMARY KEY,
    REQUESTER_ID VARCHAR2(100) NOT NULL,
    REQUESTER_NAME VARCHAR2(100) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100),
    LEAVE_TYPE VARCHAR2(30) NOT NULL,
    FROM_DATE VARCHAR2(20) NOT NULL,
    TO_DATE VARCHAR2(20) NOT NULL,
    REASON VARCHAR2(2000),
    FINAL_STATUS VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CMH.LEAVE_APPROVAL_LINE (
    ID NUMBER(19) PRIMARY KEY,
    REQUEST_ID NUMBER(19) NOT NULL,
    LINE_TYPE VARCHAR2(20) NOT NULL,
    APPROVER_ID VARCHAR2(100) NOT NULL,
    APPROVER_NAME VARCHAR2(100) NOT NULL,
    LINE_ORDER NUMBER(5) DEFAULT 1 NOT NULL,
    ACTION_STATUS VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
    ACTED_AT VARCHAR2(20),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LEAVE_LINE_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES CMH.LEAVE_REQUEST(ID)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CMH.SHIFT_ASSIGNMENT (
    ID NUMBER(19) PRIMARY KEY,
    SHIFT_DATE VARCHAR2(20) NOT NULL,
    STAFF_ID VARCHAR2(100) NOT NULL,
    STAFF_NAME VARCHAR2(100) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100),
    SHIFT_TYPE VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CMH.LEAVE_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CMH.LEAVE_APPROVAL_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CMH.SHIFT_ASSIGNMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CMH.UX_SHIFT_DATE_STAFF_TYPE ON CMH.SHIFT_ASSIGNMENT (SHIFT_DATE, STAFF_ID, SHIFT_TYPE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CMH.IDX_LEAVE_REQ_REQUESTER ON CMH.LEAVE_REQUEST (REQUESTER_ID, CREATED_AT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CMH.IDX_LEAVE_REQ_STATUS ON CMH.LEAVE_REQUEST (FINAL_STATUS, FROM_DATE, TO_DATE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CMH.IDX_LEAVE_LINE_APPROVER ON CMH.LEAVE_APPROVAL_LINE (APPROVER_ID, ACTION_STATUS, LINE_TYPE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CMH.IDX_LEAVE_LINE_REQ ON CMH.LEAVE_APPROVAL_LINE (REQUEST_ID, LINE_ORDER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CMH.IDX_SHIFT_DATE ON CMH.SHIFT_ASSIGNMENT (SHIFT_DATE, SHIFT_TYPE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
