-- Migrate legacy marker payloads in CMH.STAFF_BOARD_POST
--   LEAVE_JSON:...  -> CMH.LEAVE_REQUEST / CMH.LEAVE_APPROVAL_LINE
--   SHIFT_JSON:...  -> CMH.SHIFT_ASSIGNMENT

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CMH.LEAVE_REQUEST ADD (LEGACY_POST_ID NUMBER(19))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CMH.SHIFT_ASSIGNMENT ADD (LEGACY_POST_ID NUMBER(19))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CMH.UX_LEAVE_REQUEST_LEGACY_POST ON CMH.LEAVE_REQUEST (LEGACY_POST_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CMH.UX_SHIFT_ASSIGN_LEGACY_POST ON CMH.SHIFT_ASSIGNMENT (LEGACY_POST_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1) LEAVE request rows
INSERT INTO CMH.LEAVE_REQUEST (
  ID, REQUESTER_ID, REQUESTER_NAME, DEPARTMENT_NAME, LEAVE_TYPE,
  FROM_DATE, TO_DATE, REASON, FINAL_STATUS, CREATED_AT, UPDATED_AT, LEGACY_POST_ID
)
SELECT
  CMH.LEAVE_REQUEST_SEQ.NEXTVAL,
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.requesterId')), p.AUTHOR_ID),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.requesterName')), p.AUTHOR_NAME),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.department')), p.DEPARTMENT_NAME),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.leaveType')), '연차'),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.fromDate')), NVL(p.EVENT_DATE, TO_CHAR(p.CREATED_AT, 'YYYY-MM-DD'))),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.toDate')), NVL(p.EVENT_DATE, TO_CHAR(p.CREATED_AT, 'YYYY-MM-DD'))),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.reason')), p.TITLE),
  CASE
    WHEN UPPER(NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.finalStatus')), 'PENDING')) IN ('최종승인', 'APPROVED_FINAL') THEN 'APPROVED_FINAL'
    WHEN UPPER(NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.finalStatus')), 'PENDING')) IN ('반려', 'REJECTED') THEN 'REJECTED'
    ELSE 'PENDING'
  END,
  NVL(p.CREATED_AT, SYSDATE),
  NVL(p.UPDATED_AT, SYSDATE),
  p.ID
FROM CMH.STAFF_BOARD_POST p
WHERE p.CATEGORY = 'EVENT'
  AND p.IS_DELETED = 'N'
  AND p.CONTENT LIKE 'LEAVE_JSON:%'
  AND NOT EXISTS (
    SELECT 1 FROM CMH.LEAVE_REQUEST r WHERE r.LEGACY_POST_ID = p.ID
  );

-- 2) LEAVE approval/cc line rows
INSERT INTO CMH.LEAVE_APPROVAL_LINE (
  ID, REQUEST_ID, LINE_TYPE, APPROVER_ID, APPROVER_NAME, LINE_ORDER,
  ACTION_STATUS, ACTED_AT, CREATED_AT, UPDATED_AT
)
SELECT
  CMH.LEAVE_APPROVAL_LINE_SEQ.NEXTVAL,
  r.ID,
  NVL(jt.LINE_TYPE, 'CC'),
  NVL(TRIM(jt.APPROVER_ID), 'unknown'),
  NVL(TRIM(jt.APPROVER_NAME), NVL(TRIM(jt.APPROVER_ID), 'unknown')),
  NVL(jt.LINE_ORDER, 1),
  CASE
    WHEN UPPER(NVL(TRIM(jt.ACTION_STATUS), 'PENDING')) IN ('승인', 'APPROVED') THEN 'APPROVED'
    WHEN UPPER(NVL(TRIM(jt.ACTION_STATUS), 'PENDING')) IN ('반려', 'REJECTED', 'REJECT') THEN 'REJECTED'
    ELSE 'PENDING'
  END,
  jt.ACTED_AT,
  NVL(p.CREATED_AT, SYSDATE),
  NVL(p.UPDATED_AT, SYSDATE)
FROM CMH.STAFF_BOARD_POST p
JOIN CMH.LEAVE_REQUEST r
  ON r.LEGACY_POST_ID = p.ID
JOIN JSON_TABLE(
  SUBSTR(p.CONTENT, 12), '$.lines[*]'
  COLUMNS (
    LINE_TYPE VARCHAR2(20) PATH '$.lineType',
    APPROVER_ID VARCHAR2(100) PATH '$.approverId',
    APPROVER_NAME VARCHAR2(100) PATH '$.approverName',
    LINE_ORDER NUMBER PATH '$.lineOrder',
    ACTION_STATUS VARCHAR2(20) PATH '$.status',
    ACTED_AT VARCHAR2(20) PATH '$.actedAt'
  )
) jt
  ON 1 = 1
WHERE p.CATEGORY = 'EVENT'
  AND p.IS_DELETED = 'N'
  AND p.CONTENT LIKE 'LEAVE_JSON:%'
  AND NOT EXISTS (
    SELECT 1
    FROM CMH.LEAVE_APPROVAL_LINE l
    WHERE l.REQUEST_ID = r.ID
      AND l.LINE_TYPE = NVL(jt.LINE_TYPE, 'CC')
      AND l.APPROVER_ID = NVL(TRIM(jt.APPROVER_ID), 'unknown')
      AND l.LINE_ORDER = NVL(jt.LINE_ORDER, 1)
  );

-- 3) SHIFT assignment rows
INSERT INTO CMH.SHIFT_ASSIGNMENT (
  ID, SHIFT_DATE, STAFF_ID, STAFF_NAME, DEPARTMENT_NAME, SHIFT_TYPE,
  CREATED_BY, CREATED_AT, UPDATED_AT, LEGACY_POST_ID
)
SELECT
  CMH.SHIFT_ASSIGNMENT_SEQ.NEXTVAL,
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.date')), NVL(p.EVENT_DATE, TO_CHAR(p.CREATED_AT, 'YYYY-MM-DD'))),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.staffId')), p.AUTHOR_ID),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.staffName')), p.AUTHOR_NAME),
  NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.dept')), p.DEPARTMENT_NAME),
  CASE
    WHEN UPPER(NVL(TRIM(JSON_VALUE(SUBSTR(p.CONTENT, 12), '$.shiftType')), 'DAY')) IN ('NIGHT', '당직') THEN 'NIGHT'
    ELSE 'DAY'
  END,
  NVL(p.AUTHOR_ID, 'system'),
  NVL(p.CREATED_AT, SYSDATE),
  NVL(p.UPDATED_AT, SYSDATE),
  p.ID
FROM CMH.STAFF_BOARD_POST p
WHERE p.CATEGORY = 'SCHEDULE'
  AND p.IS_DELETED = 'N'
  AND p.CONTENT LIKE 'SHIFT_JSON:%'
  AND NOT EXISTS (
    SELECT 1 FROM CMH.SHIFT_ASSIGNMENT s WHERE s.LEGACY_POST_ID = p.ID
  );

COMMIT;
