MERGE INTO CMH.STAFF_STATUS_CODES t
USING (
    SELECT 'ACTIVE' AS code, '재직' AS label, 1 AS sort_order FROM dual
    UNION ALL SELECT 'ON_LEAVE', '휴직', 2 FROM dual
    UNION ALL SELECT 'RESIGNED', '퇴사', 3 FROM dual
) s
ON (t.CODE = s.CODE)
WHEN MATCHED THEN
  UPDATE SET
    t.LABEL = s.LABEL,
    t.SORT_ORDER = s.SORT_ORDER,
    t.IS_ACTIVE = 'Y',
    t.UPDATED_AT = SYSDATE
WHEN NOT MATCHED THEN
  INSERT (CODE, LABEL, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
  VALUES (s.CODE, s.LABEL, s.SORT_ORDER, 'Y', SYSDATE, SYSDATE);

COMMIT;
